language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-juckstrap' ]; then cd .. && eval "mv $currentfolder generator-juckstrap" && cd generator-juckstrap; fi

